name: Deploy the docs to aws

on:
  workflow_call:
    inputs:
      branch_name:
        required: false
        type: string
        default: main
      account:
        required: false
        type: string
        default: '004362422991'

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ inputs.account }}docs-stack-deploy
      cancel-in-progress: true
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ inputs.branch_name  }}
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ inputs.account }}:role/test_deployer
          role-session-name: gha-deploy-docs-stack
          aws-region: us-east-1

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .node-version
          cache: 'npm'

      - name: install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy apps to the account
        run: npm run -w cdk deploy
